module:
  aaronpero_common: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  commerce_tax: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_ex: 0
  feeds_para_mapper: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  fillpdf: 0
  filter: 0
  genpass: 0
  geolocation: 0
  geolocation_demo: 0
  geolocation_google_maps: 0
  geolocation_google_maps_demo: 0
  geolocation_google_static_maps: 0
  geolocation_google_static_maps_demo: 0
  geolocation_leaflet: 0
  help: 0
  history: 0
  image: 0
  image_class: 0
  inline_entity_form: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  search: 0
  select_or_other: 0
  serialization: 0
  shortcut: 0
  state_machine: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_node: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  youtube: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
